"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var validationMiddleware_js_1 = require("../../middlewares/validation/validationMiddleware.js");
var updateEntityById_js_1 = require("../../controllers/api/entity/updateEntityById.js");
var updateUserByIdValidator_js_1 = require("../../validation/users/updateUserByIdValidator.js");
var approvedBodyMiddleware_js_1 = require("../../middlewares/validation/approvedBodyMiddleware.js");
var entityExists_js_1 = require("../../middlewares/entityExists.js");
var entityNotMatches_js_1 = require("../../middlewares/entityNotMatches.js");
var path_1 = require("path");
var url_1 = require("url");
var router = express_1.default.Router();
var __filename = (0, url_1.fileURLToPath)(import.meta.url);
var __dirname = path_1.default.dirname(__filename);
var entity = path_1.default.basename(__dirname);
router.put('/api/users/:id', (0, approvedBodyMiddleware_js_1.default)(['username', 'email', 'password']), (0, validationMiddleware_js_1.default)(updateUserByIdValidator_js_1.updateUserValidator), (0, entityNotMatches_js_1.default)(entity), (0, entityExists_js_1.default)(entity), updateEntityById_js_1.default);
exports.default = router;
